name: flutter_analyze_reporter
description: Parse Flutter analyze output to display it within GitLab Code Quality Widget
version: 0.0.2
homepage: https://github.com/andnexus/flutter_analyze_reporter
repository: https://github.com/andnexus/flutter_analyze_reporter
issue_tracker: https://github.com/andnexus/flutter_analyze_reporter/issues

executables:
  flutter_analyze_reporter:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  lint: ^1.10.0
